version: "3.0"
services:
 web:
  build: ./web
  env_file:
   - ./web/web.env
   - ./db/db.env
  environment:
   - INIT_DB=1
  expose:
   - "8000"
  ports:
   - "8000:8000"
  command: /bin/bash start.sh
  depends_on:
   - db
  networks:
   - webnet

 db:
  build: ./db
  env_file:
   - ./db/db.env
  expose:
   - "5432"
  ports:
   - "9999:5432"
  volumes:
   - ./.data:/var/lib/postgresql/data
  networks:
   - webnet

 nginx:
  build: ./nginx
  ports:
   - "7000:7000"
  depends_on:
   - web
  networks:
   - webnet

networks:
 webnet:
