version: "3.0"
services:
 app:
  build:
    context: ./app
    dockerfile: ../dockerfiles/dockerfile-app
  env_file:
   - ./config/.secrets-app
   - ./config/app.env
  environment:
   - INIT_DB=0
  expose:
   - 8000
  ports:
   - 8000:8000
  command: gunicorn main:app -w 2 -b 0.0.0.0:8000 --timeout 1200 --reload
  volumes:
    - ./app:/usr/src/app
  depends_on:
   - db
  networks:
   - webnet
 db:
  build:
    context: ./db
    dockerfile: ../dockerfiles/dockerfile-db
  env_file:
   - ./config/.secrets-db
  expose:
   - 5432
  ports:
   - 9999:5432
  volumes:
   - metadata:/var/lib/postgresql/data
  networks:
   - webnet
 nginx:
  build:
    context: ./dockerfiles
    dockerfile: dockerfile-nginx
  volumes:
    - ./config/nginx.conf:/etc/nginx/nginx.conf
    - ./config/nip_app.conf:/etc/nginx/conf.d/nip_app.conf
  ports:
   - 7000:7000
  depends_on:
   - app
   - db
  networks:
   - webnet

networks:
 webnet:

volumes:
  metadata:
