"""empty message

Revision ID: 71759f91d2b2
Revises: 855f6ef4cd3f
Create Date: 2019-01-05 14:42:48.131240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71759f91d2b2'
down_revision = '855f6ef4cd3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('author_firstname_key', 'author', type_='unique')
    op.drop_constraint('author_lastname_key', 'author', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('author_lastname_key', 'author', ['lastname'])
    op.create_unique_constraint('author_firstname_key', 'author', ['firstname'])
    # ### end Alembic commands ###
