"""empty message

Revision ID: 7680f722a2ba
Revises: 2cd053da6867
Create Date: 2019-01-06 16:56:20.459385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7680f722a2ba'
down_revision = '2cd053da6867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('handle', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'handle')
    # ### end Alembic commands ###
